version: 1

formatters:
  standard:
    format: '%(asctime)s | %(levelname).1s | %(process)d | %(threadName).9s | [%(name)s] %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: WARNING
    formatter: standard
    filename: /tmp/warnings.log
    maxBytes: 10485760
    backupCount: 10
    encoding: utf8

root:
  level: ERROR
  handlers: [console, file]

loggers:
  release:
    level: INFO
    handlers: [console]
    propagate: no
  debug:
    level: DEBUG
    handlers: [console]
    propagate: no
